apply plugin: 'com.android.library'

android {
    namespace "com.github.clans.fab"
    compileSdk Build.compile_sdk_version

    defaultConfig {
        minSdk Build.min_sdk_version
        targetSdk Build.target_sdk_version
        versionCode Integer.parseInt(project.VERSION_CODE)
        versionName project.VERSION_NAME
    }
    buildTypes {
        release {
            minifyEnabled false
            debuggable false
        }

        debug {
            minifyEnabled false
            debuggable true
        }
    }
}

dependencies {
    implementation Libs.support_appcompat_v7
    implementation Libs.support_design
}
